// Theme presets for the book preview/export.

export const THEMES = {
  emerald: {
    name: 'زمردي — نسخ',
    fontBody: "'Noto Naskh Arabic', serif",
    fontHead: "'Noto Naskh Arabic', serif",
    pageBg: '#faf7f0',
    text: '#211c17',
    chapterBg: '#1a4d3e',
    chapterText: '#ffffff',
    subText: '#7a2e2e',
    subBorder: '#1a4d3e',
    verseBg: '#f8f2e2',
    verseBorder: '#c9a96a',
    termColor: '#7a2e2e',
    dotColor: '#b9ab8f',
    swatch: ['#1a4d3e', '#7a2e2e', '#c9a96a'],
  },
  scheherazade: {
    name: 'شهرزاد — كلاسيكي',
    fontBody: "'Scheherazade New', serif",
    fontHead: "'Scheherazade New', serif",
    pageBg: '#fbf5ec',
    text: '#231c14',
    chapterBg: '#0f4c4c',
    chapterText: '#fdf6e3',
    subText: '#9c5a1f',
    subBorder: '#0f4c4c',
    verseBg: '#f3e6cf',
    verseBorder: '#b98a3e',
    termColor: '#9c5a1f',
    dotColor: '#c2ab84',
    swatch: ['#0f4c4c', '#9c5a1f', '#b98a3e'],
  },
  sans: {
    name: 'حديث — بدون تشكيل',
    fontBody: "'Noto Sans Arabic', sans-serif",
    fontHead: "'Noto Sans Arabic', sans-serif",
    pageBg: '#ffffff',
    text: '#1c2430',
    chapterBg: '#1e3a5f',
    chapterText: '#ffffff',
    subText: '#1e3a5f',
    subBorder: '#c6551a',
    verseBg: '#eef2f6',
    verseBorder: '#9db3c8',
    termColor: '#c6551a',
    dotColor: '#c4cbd4',
    swatch: ['#1e3a5f', '#c6551a', '#9db3c8'],
  },
  sepia: {
    name: 'عتيق — أميري',
    fontBody: "'Amiri', serif",
    fontHead: "'Amiri', serif",
    pageBg: '#f4ecd8',
    text: '#3a2b1a',
    chapterBg: '#5c3a21',
    chapterText: '#f4ecd8',
    subText: '#8a3324',
    subBorder: '#5c3a21',
    verseBg: '#e9dcbd',
    verseBorder: '#a9895a',
    termColor: '#8a3324',
    dotColor: '#b7a37c',
    swatch: ['#5c3a21', '#8a3324', '#a9895a'],
  },
};

export const PAGE_SIZES = { A5: '420px', A4: '560px', Letter: '560px' };
